extends TileMapLayer

var aStar:AStar2D
var aStarGrid:AStarGrid2D
var size = self.get_used_rect().size
var path:Array[Vector2] = []

var selectedEntity: Node2D


### note: im prolly thinking later we have this one do the worldgen stuff too
### off a set of parameters based on what floor the player's on. that'll 
### already be memorized by the save so why not lol


func _ready() -> void:
	# make an aStar
	aStar = AStar2D.new()
	# make an aStarGrid
	aStarGrid = AStarGrid2D.new()
	@warning_ignore("int_as_enum_without_cast", "int_as_enum_without_match")
	aStarGrid.diagonal_mode = 1
	# set aStar grid tile size to match tilemaplayer's
	aStarGrid.cell_size = Vector2i(17,17)
	# alias so we dont go insane
	var tiles = get_used_cells()
	# creating these variables
	var northmost: int
	var eastmost: int
	var southmost: int
	var westmost: int
	# turning those variables into the outer boundaries of the aStar grid
	# go through every (existing) tile; if the previous record for farthest in that direction
	# is less in that direction than the current tile, set it as that record
	for tile in tiles:
		if northmost>tile.y: northmost = tile.y
		if eastmost<tile.x: eastmost = tile.x
		if southmost<tile.y: southmost = tile.y
		if westmost>tile.x: westmost = tile.x
	# finding the width and height of the map generated by subtracting the
	# farthest points in opposing directions
	# +1 is there because it was drawing the boundary 1 tile short east and south
	var sizeX: int = eastmost - westmost +1
	var sizeY: int = southmost - northmost +1
	# set the region of the aStarGrid to be centered at intersection between
	# westmost and northmost points, and size to be the size we just defined
	aStarGrid.region = Rect2i(westmost,northmost,sizeX,sizeY)
	# make sure the changes we've just made by defining the grid boundaries actually work
	aStarGrid.update() 
	for tile in tiles:
		if get_cell_source_id(tile)==1:aStarGrid.set_point_solid(tile,true)
	# effectively just calls _draw() in an unintrusive way

	## multiple save support is a later thing. for now only save1 is available
	## im lazy. cry about it lmao. ill do it after release probably
	# load save1 resource as a variable
	var currentFile = load("res://data//save1.tres")
	# load each expie book in expieBooks and individually iterate through
	# the results in a for loop.
	for book in currentFile.expieBooks:
		match book.expieSpecies:
			"Experi.":
				# load Experiment class as variable
				var expieToLoad = load("res://Scripts/expies/experiment.tscn").instantiate()
				# add an Experiment as child
				add_child(expieToLoad)
				print(type_string(typeof(book)))
				expieToLoad.translateBook(book)
			"Orange":
				#print(book)
				pass
			"Milky":
				#print(book)
				pass
			"Hauler":
				#print(book)
				pass
			_:
				#print("empty")
				pass

#func _unhandled_input(event: InputEvent) -> void:
#	if event.is_action_released("leftMouse"):
#		get_global_mouse_position()
#		pass
