extends TileMapLayer

#region aStar
var aStar:AStar2D
var aStarGrid:AStarGrid2D
var size = self.get_used_rect().size

func _ready() -> void:
	# make an aStar
	aStar = AStar2D.new()
	# make an aStarGrid
	aStarGrid = AStarGrid2D.new()
	# set aStar grid tile size to match tilemaplayer's
	aStarGrid.cell_size = Vector2i(17,17)
	# alias so we dont go insane
	var tiles = get_used_cells()
	# creating these variables
	var northmost: int
	var eastmost: int
	var southmost: int
	var westmost: int
	# turning those variables into the outer boundaries of the aStar grid
	# go through every (existing) tile; if the previous record for farthest in that direction
	# is less in that direction than the current tile, set it as that record
	for tile in tiles:
		if northmost>tile.y: northmost = tile.y
		if eastmost<tile.x: eastmost = tile.x
		if southmost<tile.y: southmost = tile.y
		if westmost>tile.x: westmost = tile.x
	# finding the width and height of the map generated by subtracting the
	# farthest points in opposing directions
	# +1 is there because it was drawing the boundary 1 tile short east and south
	var sizeX: int = eastmost - westmost +1
	var sizeY: int = southmost - northmost +1
	# set the region of the aStarGrid to be centered at intersection between
	# westmost and northmost points, and size to be the size we just defined
	aStarGrid.region = Rect2i(westmost,northmost,sizeX,sizeY)
	# make sure the changes we've just made by defining the grid boundaries actually work
	aStarGrid.update() 
	# effectively just calls _draw() in an unintrusive way

func _draw() -> void:
	# alias because fffFFFFFFUck draw calls
	var r = aStarGrid.region
	# draw the boundary of the map as a harmless effect for debug purposes
	draw_rect(Rect2i(Vector2i(r.position.x,r.position.y)*17,Vector2i(r.size.x,r.size.y)*17),Color.RED,false,4)

#endregion
