# writes party's books to the starting ones
# everythingmanager will write over them whenever the game is saved
# this is only used upon starting a new run
@export var expieBooks: Array[Dictionary] = [
	{
	"expieSpecies": "Experi.",
	"expieName": "Epsilon",
	"currentMood": 125,
	"currentHunger": 100,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieSpecies": "Orange",
	"expieName": "Gamma",
	"currentMood": 135,
	"currentHunger": 120,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieSpecies": "Milky",
	"expieName": "Tau",
	"currentMood": 130,
	"currentHunger": 90,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieSpecies": "Hauler",
	"expieName": "Psi",
	"currentMood": 130,
	"currentHunger": 130,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieSpecies": "null",
	"expieName": "null",
	"currentMood": 200,
	"currentHunger": 100,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieSpecies": "null",
	"expieName": "null",
	"currentMood": 200,
	"currentHunger": 100,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieSpecies": "null",
	"expieName": "null",
	"currentMood": 200,
	"currentHunger": 100,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieSpecies": "null",
	"expieName": "null",
	"currentMood": 200,
	"currentHunger": 100,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
]


@export var saveInfo: Dictionary = {
	"nodeToLoad": 1,
	#"inventoryStatus": {{{man idfk lmao wait for the bigass .csv file to be done}}}
	
}
