# writes party's books to the starting ones
# mapcore will write over them whenever the game is saved
# this is only used upon starting a new run
@export var expieBooks: Array[Dictionary] = [
	{
	"expieID": 1,
	"expieSpecies": "Experi.",
	"expieName": "Epsilon",
	"expieSerialNumber": str("E-" + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9))),
	"expieStatus": "WFSTFTSS", # waiting for someone to finish the status system
	"currentMood": 125,
	"currentHunger": 100,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"helditem": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieID": 2,
	"expieSpecies": "Orange",
	"expieName": "Gamma",
	"expieSerialNumber": str("O-" + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9))),
	"expieStatus": "WFSTFTSS",
	"currentMood": 135,
	"currentHunger": 120,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"helditem": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieID": 3,
	"expieSpecies": "Milky",
	"expieName": "Tau",
	"expieSerialNumber": str("M-" + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9))),
	"expieStatus": "WFSTFTSS",
	"currentMood": 130,
	"currentHunger": 90,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"helditem": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieID": 4,
	"expieSpecies": "Hauler",
	"expieName": "Psi",
	"expieSerialNumber": str("H-" + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9)) + str(randi_range(0,9))),
	"expieStatus": "WFSTFTSS",
	"currentMood": 130,
	"currentHunger": 130,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"helditem": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieID": 5,
	"expieSpecies": "null",
	"expieName": "null",
	"expieSerialNumber": str("N-" + str(00000)),
	"expieStatus": "WFSTFTSS",
	"currentMood": 200,
	"currentHunger": 100,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"helditem": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieID": 6,
	"expieSpecies": "null",
	"expieName": "null",
	"expieSerialNumber": str("N-" + str(00000)),
	"expieStatus": "WFSTFTSS",
	"currentMood": 200,
	"currentHunger": 100,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"helditem": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieID": 7,
	"expieSpecies": "null",
	"expieName": "null",
	"expieSerialNumber": str("N-" + str(00000)),
	"expieStatus": "WFSTFTSS",
	"currentMood": 200,
	"currentHunger": 100,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"helditem": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
	{
	"expieID": 8,
	"expieSpecies": "null",
	"expieName": "null",
	"expieSerialNumber": str("N-" + str(00000)),
	"expieStatus": "WFSTFTSS",
	"currentMood": 200,
	"currentHunger": 100,
	"currentOverallIntegrity": 150,
	"currentHeadIntegrity": 30,
	"currentTorsoIntegrity": 30,
	"currentLArmIntegrity": 30,
	"currentRArmIntegrity": 30,
	"currentLLegIntegrity": 30,
	"currentRLegIntegrity": 30,
	"pointsInSTR": 0,
	"pointsInDEX": 0,
	"pointsInCON": 0,
	"pointsInINT": 0,
	"pointsInWIS": 0,
	"pointsInCHA": 0,
	"weapon": "placeholder",
	"helditem": "placeholder",
	"armor": "placeholder",
	"gifts": [0,1,2,3,4,5,6,7],
	},
]


@export var saveInfo: Dictionary = {
	"nodeToLoad": 1,
	#"inventoryStatus": {{{man idfk lmao wait for the bigass .csv file to be done}}}
	
}
